{
    'name': 'Pagos masivos de detracciones',
    'version': '18.0.1.0.1',
    'author': 'Ganemo, Unoobi',
    'website': 'https://www.ganemo.co',
    'live_test_url': 'https://www.ganemo.co/demo',
    'summary': 'This module allows us to make massive payments of detractions.',
    'category': 'Accounting',
    'module_type': 'official',
    'depends': [
        'l10n_pe_edi',
        'base_spot',
        'l10n_pe_reports',
        'account',
        'account_batch_payment',
        'web',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/account_move.xml',
        'views/account_payment.xml',
        'views/account_batch_payment.xml',
        'wizard/account_payment_register.xml',
        'wizard/account_move_detractions.xml',
    ],
    'installable': True,
    'auto_install': False,
    'license': 'Other proprietary',
    'currency': 'USD',
    'price': 299.00
}
